lms/api/urls.py
from django.urls import path,include
from rest_framework import routers
from api.views import StandardViewSet,SubjectViewSet,LessonViewSet,UserViewSet

router=routers.DefaultRouter()
router.register(r'users',UserViewSet,basename="user")
router.register(r'standards', StandardViewSet, basename='standard')
router.register(r'subjects', SubjectViewSet,basename='subject')
router.register(r'lessons', LessonViewSet,basename='lesson')

urlpatterns = [
    path('', include(router.urls)),
]

lms/curriculum/urls.py
from django.urls import path,include
from . import views
from rest_framework.response import Response
from rest_framework import routers

app_name='curriculum'
urlpatterns = [
    path('training_level/',views.training_level, name="training_level"),
    path('trainer_subject_1/',views.trainer_subject_1, name="trainer_subject_1"),
    path('trainer_subject_2/',views.trainer_subject_2, name="trainer_subject_2"),
    path('trainer_subject_3/',views.trainer_subject_3, name="trainer_subject_3"),
    path('trainer_lesson/<slug:slug>',views.trainer_lesson,name="trainer_lesson"),
    path("trainer_lesson_detail/<slug:slug>",views.trainer_lesson_detail, name="trainer_lesson_detail"),
    path('coding/', views.coding, name="coding"),
    path('codinglessons/<slug:slug>/',views.codinglessons,name="codinglessons"),
    path('codinglesson_detail/<slug:slug>/',views.codinglesson_detail, name="codinglesson_detail"),
    path('ai/',views.ai,name="ai"),
    path('lessons/<slug:slug>/',views.lessons,name="lessons"),
    path('lesson_detail/<slug:slug>/',views.lesson_detail, name="lesson_detail"),
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path,include
from django_email_verification import urls as email_urls
# from rest_framework import routers, serializers, viewsets
# from users.models import User

# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    path('customadmin/',include(('customadmin.urls','customadmin'),namespace='customadmin')),
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('curriculum/', include(('curriculum.urls','curriculum'), namespace='curriculum')),
    path('api/', include('api.urls')),
    path('accounts/', include('allauth.urls')),
    path('email/', include(email_urls)), 
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from users.utils import activate
from .editor_views import *
from . import StudentViews

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('student/', views.StudentSignUpView.as_view(), name="user_student"),
    path('parent/', views.ParentSignUpView.as_view(), name="user_parent"),
    path('teacher/', views.TeacherSignUpView.as_view(), name="user_teacher"),
    path('principal/', views.PrincipalSignUpView.as_view(), name="user_principal"),
    path('school/', views.SchoolSignUpView.as_view(), name="user_school"),
    path('login/',views.user_login, name="login"),
    path('account/login/',views.user_login, name="login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
    path('student_report/',views.studentreport, name="student_report"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
                    template_name="registration/password_reset.html"
    ),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),name="pasword_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name="password_reset_complete"),
    path('editor/',views.editor, name="editor"),
    path('editor_index/',views.editor_index, name="editor_index"),
    path('activate/<uidb64>/<token>/',activate, name="activate"),
    path('home/',greetings,name="greetings"),
    path('home/run',runcode,name="runcode"),
    # path('student_profile/',student_home, name="student_dashboard"),
    path('enquiry',views.enquiry, name="enquiry"),
    path('message',views.message, name="message"),
    
    # URSL for Student
    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_feedback/', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save/', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', StudentViews.student_profile, name="student_profile"),
    path('student_profile_update/', StudentViews.student_profile_update, name="student_profile_update"),
    path('student_view_result/', StudentViews.student_view_result, name="student_view_result"),
]

lms/templates/ai/ai.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Courses{% endblock %}
{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;"> Courses</h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href=" {% url "users:index" %}">Home</a></li>
            <li class="disabled-text">Courses</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h6 class="white-text my-4">ABL Education leverages its intelligently curated technology tools & learning
          resources to foster 21st-century skills in kids by enabling them to tinker at an early age.</h6>
      </div>
</header>
{% endblock %}

{% block body %}
<section id="best-features" class="text-center">
  <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Master The Coding</h2>
  <!-- class row for description-->
  <div class="row d-flex justify-content-center mb-4">
    <!-- class column -->
    <div class="col-md-8 mb-5">
      <p class="grey-text">Robotics, Coding and Artificial Intelligence helps you to understand the theoretical learning in real life applications.</p>
    </div>
  </div>
  <!-- class row2 for cards -->
  <div class="row d-flex justify-content-center mb-3">
    {% for subject in subjects %}
    <div class="card mb-5 mr-4 ml-4 box-shadow-hover" style="max-width: 500px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{subject.image.url|default_if_none:'#'}}" class="card-img" alt="No image found" height="200px"
            width="200px">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h4 class="card-title" style="color:#ff5722;">{{subject.name}}</h4>
            <p class="card-text">{{subject.description|truncatechars:75}}</p>
            <p class="card-text"><small class="text-muted"></small></p>
            <a href="{% url "curriculum:lessons" slug=subject.slug %}"><button
                class="button-les"> <span> Get Lessons</span></button></a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{%endblock%}

lms/templates/ai/base_site.html
{% extends "admin/base.html" %}
 
{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}
 
{% block branding %}
<h1 id="site-name" style="font-family: cursive;" ><a href="{% url 'admin:index' %}">ABL LMS</a></h1>
{% endblock %}
 
{% block nav-global %}{% endblock %}

lms/templates/ai/lesson_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{lessons.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h3 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Chapter-{{lessons.position}}: {{lessons.name}}</h3>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'users:index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:ai'%}">Artificial Intelligence</a></li>
            <li class="disabled-text" >{{lessons.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">ABL Education leverages its intelligently curated technology tools & learning
          resources to foster 21st-century skills.</h4>
  </div>
</header>
{% endblock %}

{% block body %}

<section class="text-center">
    <h2 class="mb-3 mt-5 font-weight-bold" style="color:#ff5722;">Lecture Details</h2>
    <div class="row d-flex justify-content-center mb-3">
      <blockquote class="blockquote mt-0">
        <footer class="blockquote-footer">Created by <cite title="Source Title">{{lessons.created_by}}</cite></footer>
        </blockquote>
    </div>
    <!-- video -->
    <div class="row d-flex justify-content-center mb-3">
      <div id="player-overlay">
            <video controls>
                <source src="{{lessons.video.url}}"  type="video/mp4">
              </video>
      </div>
    </div>
</section>

<hr class="my-5" style="color:#ff5722;">

{%endblock%}

lms/templates/ai/lessons.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center
    justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold p-5 " style="color:#ff5722;">
          {{subjects.name}} </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'users:index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:ai' %}">Artificial Intelligence</a></li>
            <li class="disabled-text">{{subjects.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h6 class="white-text my-4">Robotics, Coding and Artificial Intelligence helps you to understand the theoretical learning in real life applications.</h6>
      </div>
    </header>
    {% endblock %}


    {% block body %}
    <section id="best-features" class="text-center">
      <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Deeper</h2>
      <!-- class row for description-->
      <div class="row d-flex justify-content-center mb-4">
        <!-- class column -->
        <div class="col-md-8 mb-5">
          <p class="dark-text">Robotics, Coding and Artificial Intelligence helps you to understand the theoretical learning in real life applications.</p>
        </div>
      </div>
      <!-- class row2 for cards -->
      <div class="row d-flex justify-content-center mb-3">
        {% for lesson in lessons %}
        <div class="col-sm-4 mb-4">
          <div class="card box-shadow-hover">
            <div class="card-body">
              <h5 class="card-title">Chapter-{{lesson.position}}:
                {{lesson.name}}</h5>
              <a href="{% url 'curriculum:lesson_detail' slug=lesson.slug %}">
                <button type="button" class="button-les"><span>Get Lectures</span></button>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

    </section>
  {% endblock %}